const countries = [
  {
    id: 1,
    name: "Canada",
    country_code: "CA",
    capital: "Ottawa",
    flag: "https://en.wikipedia.org/wiki/Flag_of_Canada#/media/File:Flag_of_Canada_(Pantone).svg",
    population: 38.01,
  },
  {
    id: 2,
    name: "France",
    country_code: "FR",
    capital: "Paris",
    flag: "https://en.wikipedia.org/wiki/France#/media/File:Flag_of_France.svg",
    population: 67.3,
  },
  {
    id: 3,
    name: "Argentina",
    country_code: "AR",
    capital: "Buenos Aries",
    flag: "https://en.wikipedia.org/wiki/Argentina#/media/File:Flag_of_Argentina.svg",
    population: 45.38,
  },
  {
    id: 4,
    name: "United States of America",
    country_code: "USA",
    capital: "Washington",
    flag: "https://en.wikipedia.org/wiki/United_States#/media/File:Flag_of_the_United_States_(Pantone).svg",
    population: 329.5,
  },
  {
    id: 5,
    name: "Italy",
    country_code: "IT",
    capital: "Rome",
    flag: "https://en.wikipedia.org/wiki/Italy#/media/File:Flag_of_Italy.svg",
    population: 59.55,
  },
  {
    id: 6,
    name: "Japan",
    country_code: "JP",
    capital: "Tokyo",
    flag: "https://en.wikipedia.org/wiki/Japan#/media/File:Flag_of_Japan.svg",
    population: 125.8,
  },
  {
    id: 7,
    name: "Nigeria",
    country_code: "NG",
    capital: "Lagos",
    flag: "https://en.wikipedia.org/wiki/Nigeria#/media/File:Flag_of_Nigeria.svg",
    population: 206.1,
  },
];
